export const READ_PALETTE = 'READ_PALETTE';
export const PALETTE_RECEIVED = 'PALETTE_RECEIVED';

export const CREATE_PALETTE = 'CREATE_PALETTE';
export const PALETTE_SAVED = 'PALETTE_SAVED';

export const UPDATE_PALETTE = 'UPDATE_PALETTE';
export const PALETTE_UPDATED = 'PALETTE_UPDATED';

export const DELETE_PALETTE = 'DELETE_PALETTE';
export const PALETTE_DELETED = 'PALETTE_DELETED';

export const GENERATE_PALETTE_REPORT = 'GENERATE_PALETTE_REPORT';
