export const READ_PALETTES = 'READ_PALETTES';
export const PALETTES_RECEIVED = 'PALETTES_RECEIVED';

export const SAVE_PALETTE = 'SAVE_PALETTE';
export const PALETTE_SAVED = 'PALETTE_SAVED';

export const UPDATE_PALETTE = 'UPDATE_PALETTE';
export const PALETTE_UPDATED = 'PALETTE_UPDATED';
