export const READ_PALETTE_GROUPS = 'READ_PALETTE_GROUPS';
export const PALETTE_GROUPS_RECEIVED = 'PALETTE_GROUPS_RECEIVED';

export const SAVE_PALETTE_GROUP = 'SAVE_PALETTE_GROUP';
export const PALETTE_GROUP_SAVED = 'PALETTE_GROUP_SAVED';

export const UPDATE_PALETTE_GROUP = 'UPDATE_PALETTE_GROUP';
export const PALETTE_GROUP_UPDATED = 'PALETTE_GROUP_UPDATED';
