# Travis CI Configuration file
# @link https://travis-ci.org/

# Using Java for the project
language: java
services:
  - mysql
  - postgresql
jdk:
  - openjdk10
  - openjdk11
env:
  # Doc deployment
  - DATABASE=h2 ENV=development
  # Production build
  - DATABASE=h2 ENV=production
  # MySQL
  - DATABASE=mysql ENV=development
  # Postgres
  - DATABASE=postgres ENV=development
matrix:
  include:
    # Deploys docs
    - jdk: openjdk8
      env: DATABASE=h2 ENV=development DEPLOY_DOCS=true

before_install:
  # Gets scripts
  - git clone -b v1.2.2 --single-branch https://github.com/Bernardo-MG/ci-shell-scripts.git ~/.scripts
  # Sets scripts as executable
  - chmod -R +x ~/.scripts/*
  - chmod +x ./.scripts/create-test-databases.sh
  # Prepares CI environment
  - source ~/.scripts/travis/load-travis-environment.sh
before_script:
  # Creates Maven settings
  - ~/.scripts/java/maven/create-maven-settings.sh $VERSION_TYPE
  # Creates test databases
  - ./.scripts/create-test-databases.sh
script:
  # Unit and integration tests are run
  - mvn clean verify -P $DATABASE,$ENV -Dspring.profiles.active=test,$DATABASE
after_success:
  # Documentation deployment script
  - ~/.scripts/java/maven/deploy-site.sh $DO_DEPLOY_DOCS $DATABASE,$SERVER,$ENV,deployment
