export const SET_PALETTES = 'SET_PALETTES';

export const READ_PALETTES = 'READ_PALETTES';
export const READ_PALETTES_SUCCESS = 'READ_PALETTES_SUCCESS';
export const READ_PALETTES_FAILURE = 'READ_PALETTES_FAILURE';
