export const READ_PALETTES = 'READ_PALETTES';
export const READ_PALETTES_SUCCESS = 'READ_PALETTES_SUCCESS';

export const SAVE_PALETTE = 'SAVE_PALETTE';
export const SAVE_PALETTE_SUCCESS = 'SAVE_PALETTE_SUCCESS';

export const UPDATE_PALETTE = 'UPDATE_PALETTE';
export const UPDATE_PALETTE_SUCCESS = 'UPDATE_PALETTE_SUCCESS';

export const REGISTER_PALETTE_GROUP = 'REGISTER_PALETTE_GROUP';
export const REGISTER_PALETTE_GROUP_SUCCESS = 'REGISTER_PALETTE_GROUP_SUCCESS';
